apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-checks
  namespace: team-researchops
data:
  umami.yaml: |
    filter public_website_event [daily]:
      where: created_at > TIMESTAMP_ADD('${NOW}', INTERVAL -1 DAY)

    checks for public_website_event [daily]:
      - freshness(created_at) < 2h:
          name: "Sjekker om det har kommet data siste to timer"
    
    checks for public_website:
      - duplicate_count(website_id) = 0:
          name: "Duplikater i public_website. Dette er ikke en kritisk feil med tanke på datainnsamling, men kan føre til feil i dashboards."
